name: bt_dual_bluetooth
description: Dual Bluetooth Controller (Classic + BLE)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.31.15     # BLE tarama & baÄŸlanma
  bluetooth_classic: ^0.3.2       # Classic Bluetooth (HC-06)
  flutter_joystick: ^0.2.2        # Joystick widget

flutter:
  uses-material-design: true
